# Generated by Django 5.1.2 on 2024-12-14 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_phone_remove_employee_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10), django.core.validators.RegexValidator(code='invalid_mobile', message='Mobile number must be exactly 10 digits', regex='^\\d{10}$')]),
        ),
    ]
